//! op-reth execution client service.

mod cmd;
pub mod rpc;

use std::path::{Path, PathBuf};

use anyhow::Context;
use serde::{Deserialize, Serialize};
use url::Url;

pub use cmd::OpRethCmdBuilder;

use crate::{
    ExposedPort,
    docker::{DockerImage, KupDocker, PortMapping, ServiceConfig},
    metrics::ContainerDeployTimings,
    service::{self, KupcakeService},
    services::kona_node::P2pKeypair,
};

/// Input parameters for deploying op-reth.
pub struct OpRethInput {
    /// Optional URL of the sequencer's op-reth HTTP RPC.
    /// If None (for sequencer nodes), uses self as sequencer.
    /// If Some (for validator nodes), connects to the specified sequencer.
    pub sequencer_rpc: Option<Url>,
    /// The JWT secret filename (shared with kona-node).
    pub jwt_filename: String,
    /// List of enode URLs for P2P peer discovery.
    pub bootnodes: Vec<String>,
    /// P2P keypair for deterministic node identity. Generated by the caller (L2NodeBuilder).
    pub p2p_keypair: P2pKeypair,
}

/// Default ports for op-reth.
pub const DEFAULT_HTTP_PORT: u16 = 9545;
pub const DEFAULT_WS_PORT: u16 = 9546;
pub const DEFAULT_AUTHRPC_PORT: u16 = 9551;
pub const DEFAULT_DISCOVERY_PORT: u16 = 30303;
pub const DEFAULT_LISTEN_PORT: u16 = 30303;
pub const DEFAULT_METRICS_PORT: u16 = 9001;

/// Configuration for the op-reth execution client.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct OpRethBuilder {
    /// Docker image configuration for op-reth.
    pub docker_image: DockerImage,
    /// Container name for op-reth.
    pub container_name: String,
    /// Name of the network interface
    pub net_if: Option<String>,
    /// Host for the HTTP RPC endpoint.
    pub host: String,
    /// Port for the HTTP JSON-RPC server (container port).
    pub http_port: u16,
    /// Port for the WebSocket JSON-RPC server (container port).
    pub ws_port: u16,
    /// Port for the authenticated Engine API (container port, used by kona-node).
    pub authrpc_port: u16,
    /// Port for P2P discovery (container port).
    pub discovery_port: u16,
    /// Port for listen (container port).
    pub listen_port: u16,
    /// Port for metrics (container port).
    pub metrics_port: u16,
    /// Host port for HTTP JSON-RPC. If None, not published to host.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub http_host_port: Option<u16>,
    /// Host port for WebSocket JSON-RPC. If None, not published to host.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ws_host_port: Option<u16>,
    /// Host port for authenticated Engine API. If None, not published to host.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub authrpc_host_port: Option<u16>,
    /// Host port for P2P discovery. If None, not published to host.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub discovery_host_port: Option<u16>,
    /// Host port for metrics. If None, not published to host.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metrics_host_port: Option<u16>,
    /// Port for listen. If None, not published to host.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub listen_host_port: Option<u16>,
    /// P2P secret key (32 bytes hex-encoded) for deterministic node identity.
    /// If None, a random key will be generated.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub p2p_secret_key: Option<String>,
    /// Maximum number of concurrent RPC connections (HTTP + WS combined).
    /// Defaults to effectively unlimited for local dev use.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rpc_max_connections: Option<u32>,
    /// Whether flashblocks support is enabled (uses op-rbuilder image).
    #[serde(default)]
    pub flashblocks_enabled: bool,
    /// Port for the flashblocks WebSocket server.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub flashblocks_port: Option<u16>,
    /// Whether historical proofs ExEx is enabled.
    #[serde(default)]
    pub proofs_history: bool,
    /// Log filter for stdout (e.g., "info", "debug").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub log_filter: Option<String>,
    /// Extra arguments to pass to op-reth.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub extra_args: Vec<String>,
}

/// Default Docker image for op-reth.
pub const DEFAULT_DOCKER_IMAGE: &str = "us-docker.pkg.dev/oplabs-tools-artifacts/images/op-reth";
/// Default Docker tag for op-reth.
pub const DEFAULT_DOCKER_TAG: &str = "develop";

/// Default Docker image for op-rbuilder (flashblocks-enabled execution client).
pub const DEFAULT_RBUILDER_DOCKER_IMAGE: &str = "ghcr.io/theochap/op-rbuilder";
/// Default Docker tag for op-rbuilder.
pub const DEFAULT_RBUILDER_DOCKER_TAG: &str = "v0.3.2-rc4";
/// Default port for the flashblocks WebSocket server.
pub const DEFAULT_FLASHBLOCKS_PORT: u16 = 1111;

impl Default for OpRethBuilder {
    fn default() -> Self {
        Self {
            docker_image: DockerImage::new(DEFAULT_DOCKER_IMAGE, DEFAULT_DOCKER_TAG),
            container_name: "kupcake-op-reth".to_string(),
            host: "0.0.0.0".to_string(),
            http_port: DEFAULT_HTTP_PORT,
            ws_port: DEFAULT_WS_PORT,
            authrpc_port: DEFAULT_AUTHRPC_PORT,
            discovery_port: DEFAULT_DISCOVERY_PORT,
            listen_port: DEFAULT_LISTEN_PORT,
            metrics_port: DEFAULT_METRICS_PORT,
            // Default: publish HTTP and WS to host (port 0 = OS picks), others internal only
            http_host_port: Some(0),
            ws_host_port: Some(0),
            authrpc_host_port: None,
            metrics_host_port: None,
            listen_host_port: None,
            discovery_host_port: None,
            net_if: None,
            p2p_secret_key: None,
            rpc_max_connections: Some(1_000_000),
            flashblocks_enabled: false,
            flashblocks_port: None,
            proofs_history: false,
            log_filter: None,
            extra_args: Vec::new(),
        }
    }
}

/// Handler for a running op-reth instance.
pub struct OpRethHandler {
    /// Port for P2P discovery (container port).
    pub discovery_port: u16,
    /// Docker container ID.
    pub container_id: String,
    /// Docker container name.
    pub container_name: String,
    /// The P2P listen port (used for enode URL construction).
    pub listen_port: u16,
    /// P2P keypair for this node (used for enode computation).
    pub p2p_keypair: P2pKeypair,
    /// The HTTP RPC URL for the L2 execution client (internal Docker network).
    pub http_rpc_url: Url,
    /// The WebSocket RPC URL for the L2 execution client (internal Docker network).
    pub ws_rpc_url: Url,
    /// The authenticated RPC URL for Engine API (internal Docker network, used by kona-node).
    pub authrpc_url: Url,
    /// The HTTP RPC URL accessible from host (if published). None if not published.
    pub http_host_url: Option<Url>,
    /// The WebSocket RPC URL accessible from host (if published). None if not published.
    pub ws_host_url: Option<Url>,
    /// The flashblocks WebSocket URL (internal Docker network). None if flashblocks not enabled.
    pub flashblocks_ws_url: Option<Url>,
    /// Deploy timings for metrics.
    pub deploy_timings: ContainerDeployTimings,
}

impl OpRethHandler {
    /// Returns the enode URL for this node using the container name as hostname.
    ///
    /// This computes the enode from the precomputed P2P keypair, so it's available
    /// immediately after the container is started without querying the node.
    pub fn enode(&self) -> String {
        self.p2p_keypair
            .to_enode(&self.container_name, self.discovery_port)
    }
}

impl OpRethBuilder {
    /// Returns the Docker-internal HTTP RPC URL for this node.
    pub fn docker_rpc_url(&self) -> String {
        format!("http://{}:{}/", self.container_name, self.http_port)
    }
}

impl OpRethBuilder {
    /// Build the Docker command arguments for op-reth.
    pub fn build_cmd(
        &self,
        _host_config_path: &Path,
        input: &OpRethInput,
    ) -> Result<Vec<String>, anyhow::Error> {
        let container_config_path = PathBuf::from("/data");

        let mut cmd_builder = OpRethCmdBuilder::new(
            container_config_path.join("genesis.json"),
            container_config_path.join(format!("reth-data-{}", self.container_name)),
        )
        .http_port(self.http_port)
        .ws_port(self.ws_port)
        .authrpc_port(self.authrpc_port)
        .authrpc_jwtsecret(container_config_path.join(&input.jwt_filename))
        .metrics("0.0.0.0", self.metrics_port)
        .discovery(true)
        .discovery_port(self.discovery_port)
        .bootnodes(input.bootnodes.clone())
        .extra_args(self.extra_args.clone())
        .net_if(self.net_if.clone())
        .listen_port(self.listen_port)
        .nat_dns(self.container_name.clone())
        .p2p_secret_key(&input.p2p_keypair.private_key);

        if let Some(ref url) = input.sequencer_rpc {
            cmd_builder = cmd_builder.sequencer_http(url.to_string());
        }

        if let Some(max) = self.rpc_max_connections {
            cmd_builder = cmd_builder.rpc_max_connections(max);
        }

        let flashblocks_port = self.flashblocks_port.unwrap_or(DEFAULT_FLASHBLOCKS_PORT);
        if self.flashblocks_enabled {
            cmd_builder = cmd_builder.flashblocks(flashblocks_port);
        }

        if self.proofs_history {
            let proofs_path = format!("/data/proofs-{}", self.container_name);
            cmd_builder = cmd_builder.proofs_history(proofs_path);
        }

        if let Some(ref filter) = self.log_filter {
            cmd_builder = cmd_builder.log_filter(filter);
        }

        Ok(cmd_builder.build())
    }
}

impl KupcakeService for OpRethBuilder {
    type Input = OpRethInput;
    type Output = OpRethHandler;

    fn container_name(&self) -> &str {
        &self.container_name
    }

    fn docker_image(&self) -> &DockerImage {
        &self.docker_image
    }

    async fn deploy<'a>(
        &'a self,
        docker: &'a mut KupDocker,
        host_config_path: &'a Path,
        input: OpRethInput,
    ) -> Result<OpRethHandler, anyhow::Error> {
        let container_config_path = PathBuf::from("/data");

        let p2p_keypair = input.p2p_keypair.clone();

        tracing::debug!(
            container_name = %self.container_name,
            node_id = %p2p_keypair.node_id,
            "Using P2P keypair for op-reth"
        );

        // Run proofs history initialization if enabled
        if self.proofs_history {
            let container_config_path_str = container_config_path.display().to_string();
            let chain_path = format!("{}/genesis.json", container_config_path_str);
            let datadir = format!(
                "{}/reth-data-{}",
                container_config_path_str, self.container_name
            );
            let proofs_path = format!(
                "{}/proofs-{}",
                container_config_path_str, self.container_name
            );

            // Step 1: `op-reth init` — create reth DB from genesis
            tracing::info!(
                container_name = %self.container_name,
                "Initializing reth DB from genesis for proofs history"
            );
            let init_config = ServiceConfig::new(self.docker_image.clone())
                .cmd(vec![
                    "init".to_string(),
                    "--chain".to_string(),
                    chain_path.clone(),
                    "--datadir".to_string(),
                    datadir.clone(),
                ])
                .bind(host_config_path, &container_config_path, "rw");

            docker
                .run_command(init_config)
                .await
                .context("Failed to run `op-reth init` for proofs history")?;

            // Step 2: `op-reth proofs init` — snapshot genesis state into proofs sidecar DB
            tracing::info!(
                container_name = %self.container_name,
                "Initializing proofs history sidecar DB"
            );
            let proofs_init_config = ServiceConfig::new(self.docker_image.clone())
                .cmd(vec![
                    "proofs".to_string(),
                    "init".to_string(),
                    "--chain".to_string(),
                    chain_path,
                    "--datadir".to_string(),
                    datadir,
                    "--proofs-history.storage-path".to_string(),
                    proofs_path,
                ])
                .bind(host_config_path, &container_config_path, "rw");

            docker
                .run_command(proofs_init_config)
                .await
                .context("Failed to run `op-reth proofs init` for proofs history")?;
        }

        let cmd = self.build_cmd(host_config_path, &input)?;

        // Build port mappings only for ports that should be published to host
        let port_mappings: Vec<PortMapping> = [
            PortMapping::tcp_optional(self.http_port, self.http_host_port),
            PortMapping::tcp_optional(self.ws_port, self.ws_host_port),
            PortMapping::tcp_optional(self.authrpc_port, self.authrpc_host_port),
            PortMapping::tcp_optional(self.metrics_port, self.metrics_host_port),
            PortMapping::tcp_optional(self.listen_port, self.listen_host_port),
            PortMapping::udp_optional(self.discovery_port, self.discovery_host_port),
        ]
        .into_iter()
        .flatten()
        .collect();

        let flashblocks_port = self.flashblocks_port.unwrap_or(DEFAULT_FLASHBLOCKS_PORT);
        let mut exposed_ports: Vec<ExposedPort> = vec![
            ExposedPort::tcp(self.http_port),
            ExposedPort::tcp(self.ws_port),
            ExposedPort::tcp(self.authrpc_port),
            ExposedPort::tcp(self.metrics_port),
            ExposedPort::tcp(self.listen_port),
            ExposedPort::udp(self.discovery_port),
        ];

        if self.flashblocks_enabled {
            exposed_ports.push(ExposedPort::tcp(flashblocks_port));
        }

        let service_config = ServiceConfig::new(self.docker_image.clone())
            .cmd(cmd)
            .ports(port_mappings)
            .expose_ports(exposed_ports)
            .bind(host_config_path, &container_config_path, "rw");

        let (handler, timings) = service::deploy_container(
            docker,
            &self.docker_image,
            &self.container_name,
            service_config,
        )
        .await
        .context("Failed to start op-reth container")?;

        // Build internal Docker network URLs
        let http_rpc_url = KupDocker::build_http_url(&handler.container_name, self.http_port)?;
        let ws_rpc_url = KupDocker::build_ws_url(&handler.container_name, self.ws_port)?;
        let authrpc_url = KupDocker::build_http_url(&handler.container_name, self.authrpc_port)?;

        // Build host-accessible URLs from bound ports
        let http_host_url = handler.build_host_url(self.http_port, "http")?;
        let ws_host_url = handler.build_host_url(self.ws_port, "ws")?;

        // Build flashblocks WebSocket URL if enabled
        let flashblocks_ws_url = self
            .flashblocks_enabled
            .then(|| KupDocker::build_ws_url(&handler.container_name, flashblocks_port))
            .transpose()?;

        tracing::info!(
            container_id = %handler.container_id,
            container_name = %handler.container_name,
            ?http_host_url,
            ?ws_host_url,
            ?flashblocks_ws_url,
            "op-reth container started"
        );

        Ok(OpRethHandler {
            container_id: handler.container_id,
            container_name: handler.container_name,
            listen_port: self.listen_port,
            discovery_port: self.discovery_port,
            p2p_keypair,
            http_rpc_url,
            ws_rpc_url,
            authrpc_url,
            http_host_url,
            ws_host_url,
            flashblocks_ws_url,
            deploy_timings: timings,
        })
    }
}
