{
 "title": "Op-Batcher",
 "tags": [ "public" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "query_result(op_batcher_default_info)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Channels",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(op_batcher_default_channel_num_frames{instance=~\"$instance\"})",
     "legendFormat": "num_frames"
    },
    {
     "expr": "sum(op_batcher_default_input_bytes{instance=~\"$instance\", stage=\"added\"})",
     "legendFormat": "input_bytes (added)"
    },
    {
     "expr": "sum(op_batcher_default_input_bytes{instance=~\"$instance\", stage=\"closed\"})",
     "legendFormat": "input_bytes (closed)"
    },
    {
     "expr": "sum(op_batcher_default_output_bytes{instance=~\"$instance\"})",
     "legendFormat": "output_bytes"
    },
    {
     "expr": "sum(op_batcher_default_output_bytes{instance=~\"$instance\"}) / ignoring(stage) sum(op_batcher_default_input_bytes{instance=~\"$instance\",stage=\"closed\"})",
     "legendFormat": "compr_ratio"
    }
   ]
  },
  {
   "title": "Pending L2 Blocks - by stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max by(stage) (op_batcher_default_pending_blocks_count{instance=~\"$instance\"})",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Unsafe L2 DA Bytes",
   "type": "timeseries",
   "description": "unsafe_da_bytes is an estimate of the DA footprint from all unsafe blocks loaded from the sequencer. Throttling is triggered when it exceeds a threshold (default is 3.2MB). ",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(op_batcher_default_unsafe_da_bytes{instance=~\"$instance\"})",
     "legendFormat": "unsafe_da_bytes"
    }
   ]
  },
  {
   "title": "Avg. Channel Duration [min] [30m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "1 / (sum by(cluster, namespace, stage) (rate(op_batcher_default_channel_total{instance=~\"$instance\"}[30m])) * 60)",
     "legendFormat": "{{stage}}"
    }
   ]
  },
  {
   "title": "Channel Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 15 },
   "targets": [
    {
     "expr": "op_batcher_default_channel_queue_length{instance=~\"$instance\"}",
     "legendFormat": "channel_queue_length"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "min by(layer, type) (op_batcher_default_refs_number{instance=~\"$instance\"}) > 0",
     "legendFormat": "{{layer}}-{{type}}"
    }
   ]
  },
  {
   "title": "Block Height - Diff",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "(sum(op_batcher_default_refs_number{instance=~\"$instance\", layer=\"l1\", type=\"latest\"}) > 0) - (sum(op_batcher_default_refs_number{instance=~\"$instance\", layer=\"l1_origin\", type=\"loaded\"}) > 0)",
     "legendFormat": "tip - l1_origin-loaded"
    },
    {
     "expr": "(sum(op_batcher_default_refs_number{instance=~\"$instance\", layer=\"l1\", type=\"latest\"}) > 0) - (sum(op_batcher_default_refs_number{instance=~\"$instance\", layer=\"l1_origin\", type=\"added\"}) > 0)",
     "legendFormat": "tip - l1_origin-added"
    },
    {
     "expr": "(sum(op_batcher_default_refs_number{instance=~\"$instance\", layer=\"l2\", type=\"loaded\"}) > 0) - (sum(op_batcher_default_refs_number{instance=~\"$instance\", layer=\"l2\", type=\"added\"}) > 0)",
     "legendFormat": "l2-(loaded - added)"
    }
   ]
  },
  {
   "title": "Data Rates (bytes/sec)",
   "type": "timeseries",
   "description": "When the pending_blocks_bytes dips below the threshold, a P1 alert fires",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(op_batcher_default_output_bytes_total{instance=~\"$instance\"}[20m]))",
     "legendFormat": "output_bytes[20m]"
    },
    {
     "expr": "sum(rate(op_batcher_default_pending_blocks_bytes_total{instance=~\"$instance\"}[20m]))",
     "legendFormat": "pending_blocks_bytes[20m]"
    }
   ]
  },
  {
   "title": "Blob Used Bytes Histogram Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(op_batcher_default_blob_used_bytes_bucket{instance=~\"$instance\"}[1h])))",
     "legendFormat": "95_pct_blob_bytes"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(op_batcher_default_blob_used_bytes_bucket{instance=~\"$instance\"}[1h])))",
     "legendFormat": "50_pct_blob_bytes"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(op_batcher_default_blob_used_bytes_bucket{instance=~\"$instance\"}[1h])))",
     "legendFormat": "75_pct_blob_bytes"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(op_batcher_default_blob_used_bytes_bucket{instance=~\"$instance\"}[1h])))",
     "legendFormat": "25_pct_blob_bytes"
    }
   ]
  },
  {
   "title": "Blob Used Bytes Histogram",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_batcher_default_blob_used_bytes_bucket{instance=~\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Compression Ratio Histogram Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(op_batcher_default_channel_compr_ratio_bucket{instance=~\"$instance\"}[1h])))",
     "legendFormat": "95_pct_compr_ratio"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(op_batcher_default_channel_compr_ratio_bucket{instance=~\"$instance\"}[1h])))",
     "legendFormat": "50_pct_compr_ratio"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(op_batcher_default_channel_compr_ratio_bucket{instance=~\"$instance\"}[1h])))",
     "legendFormat": "75_pct_compr_ratio"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(op_batcher_default_channel_compr_ratio_bucket{instance=~\"$instance\"}[1h])))",
     "legendFormat": "25_pct_compr_ratio"
    }
   ]
  },
  {
   "title": "Channel Compression Ratios",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_batcher_default_channel_compr_ratio_bucket{instance=~\"$instance\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Batcher Nonce",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(cluster, namespace) (op_batcher_default_txmgr_current_nonce{instance=~\"$instance\"})",
     "legendFormat": "nonce"
    }
   ]
  },
  {
   "title": "Batcher Nonce",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 44 },
   "targets": [
    {
     "expr": "max by(cluster, namespace) (op_batcher_default_txmgr_current_nonce{instance=~\"$instance\"}) != 0",
     "legendFormat": "nonce"
    }
   ]
  },
  {
   "title": "Basefee & suggested tip cap [log(wei)]",
   "type": "timeseries",
   "description": "If blob base fee is > 16x base fee, consider switching from blobs to calldata (this will be automatic if the batcher is configured for auto DA selection). Note that the batcher's internal DA switching logic uses a more involved calculation than the dashboard so may not switch DA type precisely when the panel would indicate it should -- see batcher logs filtered for cost_ratio.",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "si:wei" } },
   "targets": [
    {
     "expr": "max(op_batcher_default_txmgr_basefee_wei{instance=~\"$instance\"} != 0)",
     "legendFormat": "basefee_wei"
    },
    {
     "expr": "max(op_batcher_default_txmgr_tipcap_wei{instance=~\"$instance\"} != 0)",
     "legendFormat": "tipcap_wei"
    },
    {
     "expr": "max(op_batcher_default_txmgr_blob_basefee_wei{instance=~\"$instance\"} != 0)",
     "legendFormat": "blob_basefee_wei"
    },
    {
     "expr": "op_batcher_default_txmgr_tx_type{instance=~\"$instance\"}",
     "legendFormat": "da_type"
    }
   ]
  },
  {
   "title": "Publishing errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 44 },
   "targets": [
    {
     "expr": "op_batcher_default_txmgr_tx_publish_error_count{instance=~\"$instance\"}",
     "legendFormat": "publish_err_{{error}}_count"
    }
   ]
  },
  {
   "title": "Times",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_batcher_default_txmgr_last_publish_unix{instance=~\"$instance\"} * 1000",
     "legendFormat": "Publish Time"
    },
    {
     "expr": "op_batcher_default_txmgr_last_confirm_unix{cluster=\"$cluster\", namespace=\"$namespace\"}*1000",
     "legendFormat": "Confirm Time"
    }
   ]
  },
  {
   "title": "Balance (ETH)",
   "type": "stat",
   "description": "Current account balance in ETH",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(op_batcher_default_balance{instance=~\"$instance\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Balance (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 60 },
   "targets": [
    {
     "expr": "max(op_batcher_default_balance{instance=~\"$instance\"})",
     "legendFormat": "balance"
    }
   ]
  },
  {
   "title": "RPC Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 60 },
   "targets": [
    {
     "expr": "op_batcher_default_txmgr_rpc_error_count{instance=~\"$instance\"}",
     "legendFormat": "rpc_error_count"
    },
    {
     "expr": "rate(op_batcher_default_txmgr_rpc_error_count{cluster=\"$cluster\", namespace=\"$namespace\"}[10m])",
     "legendFormat": "rpc_error_rate"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "op_batcher_default_info{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending TXs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "max(op_batcher_default_txmgr_pending_txs{instance=~\"$instance\"})",
     "legendFormat": "pending_txs"
    }
   ]
  },
  {
   "title": "Required TX gas bumps to inclusion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "op_batcher_default_txmgr_tx_gas_bump{instance=~\"$instance\"}",
     "legendFormat": "gas_bumps"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"integrations/kubernetes/cadvisor\", cluster=\"$cluster\", namespace=\"$namespace\", container!=\"\", image!=\"\"})",
     "legendFormat": "memory usage"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", container=\"$container\", cluster=\"$cluster\"})",
     "legendFormat": "container restarts"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{container=\"$container\", cluster=\"$cluster\", namespace=\"$namespace\", resource=\"memory\", job=\"integrations/kubernetes/kube-state-metrics\"})",
     "legendFormat": "memory limit"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"batcher\", cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "go_goroutines{namespace=\"batcher\", instance=~\"$instance\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "Throttling Intensity",
   "type": "timeseries",
   "description": "Shows which controller is active an the intensity of the throttling in [0,1]. Expect positive values only when unsafe_da_bytes is over the throttling threshold.\n\nLeft axis: raw data with floating limits to make it easier to see when throttling is active. Right axis: normalised as a perecentage, showing how intense throttling really is.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "max by(type) (op_batcher_default_throttle_intensity{instance=~\"$instance\"} > 0)",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "max by(type) (op_batcher_default_throttle_intensity{instance=~\"$instance\"} > 0) * 100",
     "legendFormat": "{{type}}-%"
    }
   ]
  },
  {
   "title": "L2 Base fee, Gas used, Blob gas used",
   "type": "timeseries",
   "description": "Base fee can be affected by throttling, and (upcoming) MinBaseFee and DAFootprintBlockLimit features from Jovian. Blob gas used stores the DA footprint when Jovian activates.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "si:gas" } },
   "targets": [
    {
     "expr": "max(chain_head_basefee{instance=~\"$instance\"})",
     "legendFormat": "baseFee"
    },
    {
     "expr": "max(chain_head_gas_used{instance=~\"$instance\"})",
     "legendFormat": "gasUsed"
    },
    {
     "expr": "max(chain_head_blob_gas_used{instance=~\"$instance\"})",
     "legendFormat": "blobGasUsed"
    }
   ]
  }
 ]
}